// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "ATQ - Director": databind Resource Client
//
// Command:
// $ goagen
// --design=github.com/mtenrero/ATQ-Director/http/design
// --out=$(GOPATH)/src/github.com/mtenrero/ATQ-Director
// --version=v1.3.1

package client

import (
	"bytes"
	"context"
	"fmt"
	"io"
	"mime/multipart"
	"net/http"
	"net/url"
	"os"
	"path/filepath"
)

// ListDatabindPath computes a request path to the list action of databind.
func ListDatabindPath() string {

	return fmt.Sprintf("/api/databind/list")
}

// List of uploaded and available files
func (c *Client) ListDatabind(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewListDatabindRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewListDatabindRequest create the request corresponding to the list action endpoint of the databind resource.
func (c *Client) NewListDatabindRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}

// UploadDatabindPath computes a request path to the upload action of databind.
func UploadDatabindPath() string {

	return fmt.Sprintf("/api/databind/upload")
}

// Upload new zipped file for later usage with a Task
func (c *Client) UploadDatabind(ctx context.Context, path string, payload *UploadPayload) (*http.Response, error) {
	req, err := c.NewUploadDatabindRequest(ctx, path, payload)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewUploadDatabindRequest create the request corresponding to the upload action endpoint of the databind resource.
func (c *Client) NewUploadDatabindRequest(ctx context.Context, path string, payload *UploadPayload) (*http.Request, error) {
	var body bytes.Buffer
	w := multipart.NewWriter(&body)
	{
		_, file := filepath.Split(payload.File)
		fw, err := w.CreateFormFile("file", file)
		if err != nil {
			return nil, err
		}
		fh, err := os.Open(payload.File)
		if err != nil {
			return nil, err
		}
		defer fh.Close()
		if _, err := io.Copy(fw, fh); err != nil {
			return nil, err
		}
	}
	if err := w.Close(); err != nil {
		return nil, err
	}
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("POST", u.String(), &body)
	if err != nil {
		return nil, err
	}
	header := req.Header
	header.Set("Content-Type", w.FormDataContentType())
	return req, nil
}
