language: go

services:
  - docker

go:
  - tip
  - master

before_install:
# Setup dependency management tool
- curl -L -s https://github.com/golang/dep/releases/download/v0.3.1/dep-linux-amd64 -o $GOPATH/bin/dep
- chmod +x $GOPATH/bin/dep
- docker swarm init

install:
  - dep ensure
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

before_script:
  - go get -t -d -v ./... 

script:
  - go test ./... -race -coverprofile=coverage.txt -covermode=atomic
  - go build -v ./...
  - $GOPATH/bin/goveralls -service=travis-ci

after_success:
  - bash <(curl -s https://codecov.io/bash)