port: 8080
glusterpath: /Users/marcostenrero/Documents/goProjects/src/github.com/mtenrero/ATQ-Director
images:
  - imageName: mtenrero/jmeter
    args:
      - name: MODE
        required: true
      - name: TEST_NAME
        required: false
      - name: REMOTES
        required: false