version: '3.3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.0
    environment:
      - cluster.name=elasticsearch
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet
  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.0
    environment:
      SERVER_NAME: localhost
      ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
      - 5601:5601
    networks:
      - esnet

  grafana:
    image: grafana/grafana:latest
    ports:
      - "80:3000"
    volumes:
      - grafana:/var/lib/grafana
  atq:
    image: tenrero/atq:latest
    ports:
      - "8080:8080"
    volumes:
      - /mnt/gluster/atq:/gluster:rw
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: global
      placement:
        constraints: 
          - node.role == manager

volumes:
  esdata:
  grafana:

networks:
  esnet: