// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "ATQ - Director": Application Resource Href Factories
//
// Command:
// $ goagen
// --design=github.com/mtenrero/ATQ-Director/http/design
// --out=$(GOPATH)/src/github.com/mtenrero/ATQ-Director
// --version=v1.3.1

package app
